### ISSUE TITLE
Rename "Click multi"

### ISSUE THREAD

**Issue by elescamilla** [lanl/Memento-Tracer-Extention#13]
The "click multi" option allows users to create a loop. However, that is not conveyed in label. 

Definition of done: 
* Present other options
* Implement label change

**Comment by talyacooper** [comment]
Related to this -- I am wondering if we could rename the dropdown menu of options that "Click multi" is a part of to be called something like "Options" or "Click Options" instead of just "Click," to give the user clues as to why they might be interested in looking at the dropdown. I don't think it's immediately obvious in its current state.

![Screen Shot 2022-09-21 at 12 09 40 PM](https://user-images.githubusercontent.com/54854192/191555868-b39415d6-e40e-4652-957d-18257210a877.png)

**Comment by talyacooper** [comment]
Vicky and I brainstormed about different names for "Click Multi" that would be more descriptive of what this function does for a user. It's honestly quite difficult to describe and we're not thrilled with any of these:
Loop & click
Click workflow
Loop in a loop
Loop until clicked
